name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  ci:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run linter
        run: |
          flake8 app/ tests/

      - name: Run unit tests
        run: |
          python -m pytest tests/

      - name: Build Docker image
        run: |
          docker build -t myapp:test .
